/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
        
import React, { useEffect, useRef } from 'react'
import { useAnimations, useGLTF, 

 } from '@react-three/drei'
import { useCharacterAnimations } from '../../contexts/CharacterAnimations'


export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/druid/model.gltf')
  const {actions,names}=useAnimations(animations,group)
  const {setAnimations,animationIndex}=useCharacterAnimations()
  useEffect(()=>{
    setAnimations(names)
  },[])
  useEffect(()=>{
    actions[names[animationIndex]].reset().fadeIn(0.5).play();
    return ()=>{actions[names[animationIndex]]?.fadeOut(0.5)}
  },[animationIndex])

  return (
    <group ref={group} {...props} dispose={null}>
<group scale={1.91} >
<primitive object={nodes.root} />
<skinnedMesh geometry={nodes.druid.geometry} material={materials.color_main} skeleton={nodes.druid.skeleton} />
</group>

    </group>
  )
}

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/druid/model.gltf')